global:
    game:
        board_size: 8
    model_directory: data/model

players:
    random_1:
        engine: RandomPlayer

    random_2:
        engine: RandomPlayer

    dlp_1:
        engine: DeepLearningPlayer
        load: max
        board_size: 8
        hide: true

    dlp_2:
        engine: DeepLearningPlayer
        load: max
        board_size: 8
        hide: true

    keras_1:
        engine: KerasPlayer
        load: max
        board_size: 8

    keras_2:
        engine: KerasPlayer
        load: max
        board_size: 8

processes:
    random:
        players:
            random_1: null
            random_2: null
        first: random
        game:
            board_size: 8
        times: 1000

    keras_train:
        players:
            keras_1:
                mode: train
            keras_2:
                mode: train
        first: random
        game:
            board_size: 8
        times: 10000

    keras_test:
        players:
            keras_1:
                mode: test
            keras_2:
                mode: test
        first: random
        game:
            board_size: 8
        times: 1000

    keras_check:
        players:
            keras_1:
                mode: test
            random_1: null
        first: random
        game:
            board_size: 8
        times: 1000

    dlp_train:
        players:
            dlp_1:
                mode: train
            dlp_2:
                mode: train
        first: random
        game:
            board_size: 8
        times: 10000

    dlp_test:
        players:
            dlp_1:
                mode: test
            dlp_2:
                mode: test
        first: random
        game:
            board_size: 8
        times: 1000

    dlp_check:
        players:
            dlp_1:
                mode: test
            random_1:
                mode: null
        first: random
        game:
            board_size: 8
        times: 1000
